force-app/main/default/objects/Custom_Exception__c/Custom_Exception__c.object-meta.xml
<CustomObject>
    <label>Custom Exception</label>
    <nameField>
        <displayFormat>CE-{00000000}</displayFormat>
        <label>Custom Exception Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Exception__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Custom_Exceptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Exception__c/fields/Error_RecordId__c.field-meta.xml
<CustomField>
    <fullName>Error_RecordId__c</fullName>
    <label>Error RecordId</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Exception__c/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <label>Exception Message</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Custom_Exception__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Custom Exceptions</relationshipLabel>
    <relationshipName>Custom_Exceptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Exception__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipName>Custom_Exceptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Exception__c/fields/Request_Json__c.field-meta.xml
<CustomField>
    <fullName>Request_Json__c</fullName>
    <label>Request Json</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Custom_Exception__c/fields/Response_Json__c.field-meta.xml
<CustomField>
    <fullName>Response_Json__c</fullName>
    <label>Response Json</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Custom_Exception__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <label>StackTrace</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Custom_Exception__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Request</fullName>
            </value>
            <value>
                <fullName>Response</fullName>
            </value>
            <value>
                <fullName>Callout</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CBTN_Utility.cls
public class CBTN_Utility {
    Public Static void LogException(ID recId , Exception ex,String className){
        
        Custom_Exception__c ce = new Custom_Exception__c();
        ce.ClassName__c = classname ;
        ce.Exception_Message__c = ex.getMessage() + ' : ' + ex.getCause();
        ce.Line_Number__c = String.valueOf(ex.getLineNumber());
       // ce.MethodName__c = ex.getStackTraceString();
       // ce.Exception_Type__c = ex.getTypeName();
       // ce.StackTrace__c = ex.getStackTraceString();
        //ce.User__c = UserInfo.getUserId();
        ce.Error_RecordId__c = String.valueOf(recId) ;
        ce.Type__c = 'Error';
        if(recId != null && String.valueOf(recId).startsWith('006')){
            
            ce.OpportunityId__c = recId;
            Opportunity opp = [select Id,AccountId from Opportunity Where Id =: recid];
            ce.Account__c = opp.AccountId;
            
        }
       else if(recId != null && String.valueOf(recId).startsWith('0Q0')){
            
            ce.Quote__c = recId;
            Quote qRec = [select Id,AccountId,opportunityId from Quote Where Id =: recid];
           	ce.OpportunityId__c = qRec.opportunityId;
            ce.Account__c = qRec.AccountId;
            
        }
        
        
        insert ce;
            
    }
     Public Static void LogException(ID recId , Exception ex){
        
        Custom_Exception__c ce = new Custom_Exception__c();
        ce.Exception_Message__c = ex.getMessage() + ' : ' + ex.getCause();
        ce.Line_Number__c = String.valueOf(ex.getLineNumber());
       // ce.MethodName__c = ex.getStackTraceString();
       // ce.Exception_Type__c = ex.getTypeName();
       // ce.StackTrace__c = ex.getStackTraceString();
        //ce.User__c = UserInfo.getUserId();
        ce.Error_RecordId__c = String.valueOf(recId) ;
        ce.Type__c = 'Error';
        if(recId != null && String.valueOf(recId).startsWith('006')){
            
            ce.OpportunityId__c = recId;
            Opportunity opp = [select Id,AccountId from Opportunity Where Id =: recid];
            ce.Account__c = opp.AccountId;
            
        }
       else if(recId != null && String.valueOf(recId).startsWith('0Q0')){
            
            ce.Quote__c = recId;
            Quote qRec = [select Id,AccountId,opportunityId from Quote Where Id =: recid];
           	ce.OpportunityId__c = qRec.opportunityId;
            ce.Account__c = qRec.AccountId;
            
        }
        
        
        insert ce;
            
    }
    Public static void LogRequestAndResponse(Id recId ,Integer StatusCode,String JsonReq,string JsonRes){
        
        Custom_Exception__c ce = new Custom_Exception__c();
         ce.Error_RecordId__c =String.valueOf(recId); 
          ce.Type__c = 'Callout';
          ce.Status_Code__c = StatusCode;
        if(recId != null && String.valueOf(recId).startsWith('006')){
            ce.OpportunityId__c = recId;
        }
         if(recId != null && String.valueOf(recId).startsWith('001')){
            ce.Account__c = recId;
        }
        
         if(recId != null && String.valueOf(recId).startsWith('0Q0')){
            ce.Quote__c = recId;
        }
         ce.Request_Json__c= JsonReq;
         ce.Response_Json__c= JsonRes;

        insert ce;
    }
    
    
    Public static void LogRequestAndResponse(list<Id> recIds,Integer StatusCode,String JsonReq,string JsonRes){
        
        Custom_Exception__c ce = new Custom_Exception__c();
         ce.Error_RecordId__c =String.valueOf(recIds[0]); 
          ce.Type__c = 'Callout';
          ce.Status_Code__c = StatusCode;

        for(ID id : recIds){
            
            if(id != null && String.valueOf(id).startsWith('006')){
            
            ce.OpportunityId__c =id;
      	  }
            
            if(id != null && String.valueOf(id).startsWith('001')){
            
            ce.Account__c = id;
      	  }
            
            if(id != null && String.valueOf(id).startsWith('0Q0')){
            
            ce.Quote__c =id ;
      	  }
            
            
        }
        
        
        
         ce.Request_Json__c= JsonReq;
         ce.Response_Json__c= JsonRes;

        insert ce;
    }
    
    Public static void LogRequestAndResponse(Id recId ,String JsonReq,string JsonRes){
        
        Custom_Exception__c ce = new Custom_Exception__c();
         ce.Error_RecordId__c =String.valueOf(recId); 
         ce.Type__c = 'Callout';
        if(recId != null && String.valueOf(recId).startsWith('006')){
            
            ce.OpportunityId__c = recId;
        }
         ce.Request_Json__c= JsonReq;
         ce.Response_Json__c= JsonRes;

        insert ce;
    }
}